### ISSUE TITLE
Allow connector to create an AWS session with default credentials

### ISSUE THREAD

**Issue by dfreiman-hbo** [uber/athenadriver#44]
In some environments it may be preferable for the AWS sdk to determine the credentials instead of having them passed in.

Proposal:
If the `AWS_SDK_LOAD_CONFIG` environment variable is unset and the access id is not passed, the session should be created with just the region. Credentials will be read by the AWS sdk.

Details:
1. Add a new condition to connector.go Connect() if c.config.GetAccessID() is empty.
2. Update Readme to include enhancement
3. I might need guidance on how to include new tests. The current tests are missing credentials.

I am willing to create a pull request for this if approved (and when my employer's legal dept approves).

**Comment by dfreiman-hbo** [comment]
Should I have bumped the version as done in https://github.com/uber/athenadriver/pull/37/commits/137ed81c9220d57d99d94ab3332f3aaa9a047728 ?

**Comment by henrywoo** [comment]
Thanks @dfreiman-hbo  I will do it over the weekend.
